hit the API
Danfall369/Leaderboard pull request #2
Opened 2023-04-13 18:48 UTC by Danfall369

adding function to get, add and deploy with an API

Hi there,

I have implemented the "Refresh" and "Submit" buttons as per the requirements. The "Refresh" button retrieves all scores for a game created by the user from the API, and the "Submit" button saves a score for a game created by the user by sending data to the API.

To achieve this, I used arrow functions instead of the function keyword and utilized the async and await JavaScript features to consume the API and parse the JSON data.

Please review my code changes and let me know if any further modifications are required.

Thank you!

2023-04-13 19:44 UTC, Shisui6 requested changes
Hi @Danfall369, 

# Requires Changes 🍀
You have done a great job so far!👏👏
Your design is good 🖼️, and your code follows best practices. However, there are a few issues that you still need to work on🪲.

## Highlights
- Nice use of async and await ✅
- Nice use of arrow functions✅


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 19:44 UTC, Shisui6 commented on src/index.js
> +  postData({ user: name, score });
According to the project requirements, each submit action should post a single score to the API. Currently, after the form is submitted and the refresh button is clicked, the submitted score shows up twice as seen in the video below:

https://user-images.githubusercontent.com/37116322/231866256-efa38a02-a12f-446f-8c89-d933c1762902.mp4

Please take a look at your post functions and ensure that the score is only submitted once🙏

2023-04-13 22:38 UTC, codecaiine requested changes
Hi @Danfall369 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Good usage of arrow functions ✔️
async and await with the fetch work as expected ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 22:38 UTC, codecaiine commented on src/index.js
> +  postData({ user: name, score });
- [ ] Good job so far but the issue pointed out by the previous reviewer is still persisting. In fact, when we submitted a score and hit the refresh button it come up twice. You can see more details when the Video is shared down ⬇️. Please make sure that the score came once as required for this project 👍 
https://www.loom.com/share/f81c752b5e5447dd80595ecc9cee1461

- [ ] [OPTIONAL] Please make sure that when the score is submitted the input is reset Because we can think that the information is not gone and submit several times since there is no confirmation message 😄

2023-04-14 01:48 UTC, didierganthier approved these changes
Hi @Danfall369 ,

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

<img src="https://media.giphy.com/media/l9CSJHK88kMTe/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct Gitflow ✔️ 

## Optional Suggestions 💡
- N/A

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

2023-04-14 02:07 UTC, merged